version: "3.4"
services:
    web:
        build: .
        environment:
            - ASPNETCORE_URLS=http://+:5000
        ports:
            - "8020:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Passw0rd123!"
            ACCEPT_EULA: "Y"